### ISSUE TITLE
Pi Zero W Issues

### ISSUE THREAD

**Issue by char61462** [NickJongens/PiEvilTwin#3] opened 2020-12-17 16:10 UTC
I have installed this on my Pi Zero W several times over the last week and it's not working right out the box. Here are my configs:

Dnsmasq

interface=br0
listen-address=10.1.1.1
no-hosts
dhcp-range=10.1.1.2,10.1.1.254,10m
dhcp-option=option:router,10.1.1.1
dhcp-authoritative

address=/apple.com/10.1.1.1
address=/appleiphonecell.com/10.1.1.1
address=/airport.us/10.1.1.1
address=/akamaiedge.net/10.1.1.1
address=/akamaitechnologies.com/10.1.1.1
address=/microsoft.com/10.1.1.1
address=/msftncsi.com/10.1.1.1
address=/msftconnecttest.com/10.1.1.1
address=/google.com/10.1.1.1
address=/gstatic.com/10.1.1.1
address=/googleapis.com/10.1.1.1
address=/android.com/10.1.1.1

Hostapd
interface=wlan0
channel=6
hw_mode=g

ssid=Google Free WiFi

bridge=br0
auth_algs=1
wmm_enabled=0

Here is the output from PiEvilTwin.sh

root@raspberrypi:/home/pi/PiEvilTwin# ./PiEvilTwinStart.sh 
Current MAC:   00:03:cf:4a:3b:8d (Muxcom, Inc.)
Permanent MAC: b8:27:eb:22:a7:97 (Raspberry Pi Foundation)
New MAC:       00:21:eb:a9:2b:b6 (ESP SYSTEMS, LLC)
Configuration file: /etc/hostapd/hostapd.conf
Could not set channel for kernel driver
Interface initialization failed
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
wlan0: Unable to setup interface.
wlan0: interface state DISABLED->DISABLED
wlan0: AP-DISABLED 
wlan0: CTRL-EVENT-TERMINATING 
hostapd_free_hapd_data: Interface wlan0 wasn't started
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
net.ipv4.ip_forward = 1

Any help would be great! Thanks!

**Comment by NickJongens** [comment] 2020-12-17 18:43
Duplicate of #2 - closing

**Closed** 2020-12-17 18:43 UTC
